# numpy array operation

In [1]:
import numpy as np

In [2]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )


In [3]:
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [4]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [5]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [6]:
print("Size of array: ", arr.size)

Size of array:  6


# creation of arrays


In [7]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [8]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'int')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [9]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)
  


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [11]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)
  


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [12]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
  
newarr = arr.reshape(2, 2, 3)
  

In [13]:
print(newarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [14]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
  
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)



Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# array indexing

In [15]:
import numpy as np

In [16]:
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
  
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
  

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [17]:
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
  


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [18]:
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)



Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Operations on single array

In [19]:
import numpy as np
  
a = np.array([1, 2, 5, 3])

In [20]:
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [21]:
print ("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [22]:
print ("Squaring each element:", a**2)
 

Squaring each element: [ 1  4 25  9]


In [23]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
  
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)



Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


# Unary operators

In [24]:
import numpy as np
  
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
  

In [25]:
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
  

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [26]:
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
  

Column-wise minimum elements: [1 1 2]
