# numpy array operation

In [1]:
import numpy as np

In [2]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )


In [3]:
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [4]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [5]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [6]:
print("Size of array: ", arr.size)

Size of array:  6


# creation of arrays


In [7]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [8]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'int')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [9]:

c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)
  


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [11]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)
  


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [12]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
  
newarr = arr.reshape(2, 2, 3)
  

In [13]:
print(newarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [14]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
  
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)



Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# array indexing

In [15]:
import numpy as np

In [16]:

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
  
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
  

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [17]:
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
  


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [18]:
# boolean array indexing example
cond = arr > 0
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)



Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Operations on single array

In [19]:
import numpy as np
  
a = np.array([1, 2, 5, 3])

In [20]:
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [21]:
print ("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [22]:
print ("Squaring each element:", a**2)
 

Squaring each element: [ 1  4 25  9]


In [23]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
  
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)



Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


# Unary operators

In [24]:
import numpy as np
  
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
  

In [25]:
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
  

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [26]:
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
  

Column-wise minimum elements: [1 1 2]


# MATRIX OPERATIONS

In [1]:
import numpy as np


In [2]:
gfg = np.matrix('[64, 1; 12, 3]')

In [5]:
a = gfg.max()

In [6]:
print(a)

64


In [7]:
b = gfg.min()

In [8]:
print(b)

1


In [9]:
c= gfg.take(2)

# 

In [10]:
print(c)

[[12]]


In [11]:
d =gfg.take(0,1)

In [12]:
print d

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (Temp/ipykernel_10704/1159321972.py, line 1)

In [13]:
print(d)

[[64 12]]


In [14]:
import numpy as np

In [15]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

In [16]:
column_to_be_added = np.array([1, 2, 3])
result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))

In [17]:
print ("resultant array", str(result))


resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [18]:
#USING COLUMN STACK METHOD

In [19]:
import numpy as np

In [20]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

In [21]:
print("initial_array : ", str(ini_array));
# Array to be added as column
column_to_be_added = np.array([1, 2, 3])
 

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]


In [22]:
result = np.column_stack((ini_array, column_to_be_added))
 
# printing result
print ("resultant array", str(result))


resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


# inversing a matrix

In [23]:
import numpy as np
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  

In [24]:
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [25]:
#converting matrix to list
gfg = np.matrix('[4, 1, 12, 3]')
              
# applying matrix.tolist() method
a = gfg.tolist()
    
print(a)

[[4, 1, 12, 3]]


In [26]:
d = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
b = d.tolist()

In [27]:
print(b)

[[4, 1, 9], [12, 3, 1], [4, 5, 6]]
